config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/cookiecutter-web:
      branch: main
      repo: https://github.com/m-team-kit/cookiecutter-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/cookiecutter-web git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-magenta-rabbit.sh
        container: qc.acc_stealthy-alizarin-giraffe
  QC.Doc:
    repos:
      github.com/m-team-kit/cookiecutter-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-purple-avocet.sh
        container: qc.doc_leaky-buff-bordeaux
      github.com/m-team-kit/cookiecutter-web git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-alizarin-mist.sh
        container: qc.doc_chewy-lavender-dingo
  QC.Lic:
    repos:
      github.com/m-team-kit/cookiecutter-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-burgundy-tarantula.sh
        container: qc.lic_thirsty-amber-axolotl
  QC.Ver:
    repos:
      github.com/m-team-kit/cookiecutter-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-dandelion-setter.sh
        container: qc.ver_goopy-platinum-moose
timeout: 5400
