config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/m-team-kit/cookiecutter-web:
      branch: main
      repo: https://github.com/m-team-kit/cookiecutter-web
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/cookiecutter-web git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-blue-beetle.sh
        container: qc.acc_foggy-corn-wildebeest
  QC.Doc:
    repos:
      github.com/m-team-kit/cookiecutter-web find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-grey-setter.sh
        container: qc.doc_shaggy-ultramarine-bracke
      github.com/m-team-kit/cookiecutter-web git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-beige-cat.sh
        container: qc.doc_squeaky-coral-octopus
  QC.Lic:
    repos:
      github.com/m-team-kit/cookiecutter-web licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-aquamarine-maltese.sh
        container: qc.lic_seedy-asparagus-anteater
  QC.Ver:
    repos:
      github.com/m-team-kit/cookiecutter-web get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-teal-harrier.sh
        container: qc.ver_sloppy-cyan-monster
timeout: 5400
